INSERT INTO dbo.sustenance ([name]) VALUES ('Garlic-Grilled Shrimp');
INSERT INTO dbo.sustenance ([name]) VALUES ('Admiral''s Feast');
INSERT INTO dbo.sustenance ([name]) VALUES ('Shrimp Linguini Alfredo');
INSERT INTO dbo.sustenance ([name]) VALUES ('Parrot Isle Jumbo Coconut Shrimp');
INSERT INTO dbo.sustenance ([name]) VALUES ('Seaside Shrimp Trio');
INSERT INTO dbo.sustenance ([name]) VALUES ('Shrimp Your Way');
INSERT INTO dbo.sustenance ([name]) VALUES ('Walt''s Favorite Shrimp');
INSERT INTO dbo.sustenance ([name]) VALUES ('Create Your Own Combination');
INSERT INTO dbo.sustenance ([name]) VALUES ('Snow Crab Legs');
INSERT INTO dbo.sustenance ([name]) VALUES ('Crab Linguini Alfredo');
INSERT INTO dbo.sustenance ([name]) VALUES ('Bar Harbor Lobster Bake');
INSERT INTO dbo.sustenance ([name]) VALUES ('Roasted Maine Lobster Bake');
INSERT INTO dbo.sustenance ([name]) VALUES ('Maine Lobster Tail Soaked in Butter and Lemon');
INSERT INTO dbo.sustenance ([name]) VALUES ('Ultimate Seafood Feast(R)');
INSERT INTO dbo.sustenance ([name]) VALUES ('Wood-Grilled Lobster, Shrimp and Salmon');
INSERT INTO dbo.sustenance ([name]) VALUES ('Live Maine Lobster');
INSERT INTO dbo.sustenance ([name]) VALUES ('Rock Lobster Tail');
INSERT INTO dbo.sustenance ([name]) VALUES ('Fried Sole');
INSERT INTO dbo.sustenance ([name]) VALUES ('Parmesan-Crusted Fresh Tilapia');
INSERT INTO dbo.sustenance ([name]) VALUES ('Hand-Battered Fish and Chips');
INSERT INTO dbo.sustenance ([name]) VALUES ('Salmon New Orleans');
INSERT INTO dbo.sustenance ([name]) VALUES ('NY Strip* and Rock Lobster Tail');
INSERT INTO dbo.sustenance ([name]) VALUES ('Wood-Grilled Peppercorn Sirloin');
INSERT INTO dbo.sustenance ([name]) VALUES ('Maple-Glazed Chicken');
INSERT INTO dbo.sustenance ([name]) VALUES ('Cajun Chicken Linguini Alfredo');
INSERT INTO dbo.sustenance ([name]) VALUES ('Center-Cut New York Strip* Steak');
INSERT INTO dbo.sustenance ([name]) VALUES ('Wood-Grilled Peppercorn Sirloin* and Shrimp');
INSERT INTO dbo.sustenance ([name]) VALUES ('Wood-Grilled Tacos');
INSERT INTO dbo.sustenance ([name]) VALUES ('Asian Chicken Salad');
INSERT INTO dbo.sustenance ([name]) VALUES ('Steak and White Cheese Sandwich');
INSERT INTO dbo.sustenance ([name]) VALUES ('Hot Dog Surprise');
INSERT INTO dbo.sustenance ([name]) VALUES ('Cheeseburger with the Works');
INSERT INTO dbo.sustenance ([name]) VALUES ('Fried Mozzarella');
GO